### ISSUE TITLE
Previous and next links

### ISSUE THREAD

**Issue by govuk-design-system** [alphagov/govuk-design-system-backlog#110]
## What
Help users navigate through a linear sequence of information pages.

Example on GOV.UK

![screen shot 2018-02-21 at 11 00 04](https://user-images.githubusercontent.com/33149131/36476655-6bff6ca4-16f6-11e8-9f59-5cf67c9c88b6.png)

## Why

Services that use this pattern:

 - [GOV.UK guidance](https://www.gov.uk/bullying-at-school/reporting-bullying)

## Anything else
- Land Registry has a version called [Pagination simple](http://land-registry-elements.herokuapp.com/pagination-simple/demo) 
- Related component: [Pagination](https://github.com/alphagov/govuk-design-system-backlog/issues/77)

**Comment by nickcolley** [comment]
See https://govuk-publishing-components.herokuapp.com/component-guide/previous_and_next_navigation for the component used on GOV.UK Publishing for example on (https://www.gov.uk/search?q=document&start=20)

**Comment by igloosi** [comment]
GOV.UK Pagination is now stacked
<img width="671" alt="screen shot 2018-07-23 at 13 58 21" src="https://user-images.githubusercontent.com/3758555/43077840-874152aa-8e80-11e8-8427-aee4f7f60682.png">

**Comment by Ciandelle** [comment]
Merged with issue #77 pagination Thank you everyone who contributed.
