### ISSUE TITLE
Small versions of checkboxes and radios

### ISSUE THREAD

**Issue by owenm6** [alphagov/govuk-design-system-backlog#121]
## Reason for variation
The size of the current GOV.UK components aren't ideal for some caseworking and multi use services with more than one thing per page. 

## Design variation
* smaller by 13px which we’ve found is a good compromise between size and usability
* reduced the padding on the labels

## Research
We have teams using these components in their services and so far they have performed well with no problems found.

Some access needs research has been done with caseworkers and no issues were found.

## Issues
Components have been used on grey background colours. The components don't have a fill so this reduces the contrast and usability. 

[Prototype code for checkboxes](https://home-office-digital-patterns.herokuapp.com/components/checkboxes)
[Prototype code for radios](https://home-office-digital-patterns.herokuapp.com/components/radios)

**Comment by timpaul** [comment]
Thanks for this Michael. We think the rationale behind having smaller controls is a good one but we'll need to figure out how to implement the idea using GOV.UK Frontend.

What would help in the meantime would be to consider the guidance we'd need to provide so that users of the design system knew when it was appropriate to use smaller versions of the controls.

**Comment by joelanman** [comment]
I'm not sure if they're intended to be, but I'm not sure the linked examples are good use cases for small inputs.

In my experience, a good use case is for example [filtering search results](https://www.gov.uk/cma-cases), where you have filters in a relatively small column. Large inputs here mean filters take up a lot of room.

**Comment by owenm6** [comment]
@timpaul @joelanman Something along these lines:

## When to use this component
On more complex interfaces when there is more then one thing on a page.

When the component is not part of the primary action on a page.

A common use would be filtering search results.

**Comment by timpaul** [comment]
Yeah, I think those are the 2 main use cases: high information density and secondary functions. 

We'll need to figure out where to put this guidance though - do we repeat it on every form component page, or say it once somewhere else? Should every form component have a 'small' example? What about patterns with form-based examples? @amyhupe ?

**Comment by joelanman** [comment]
Maybe this is an extension of our typography standard. We say to use 19px by default, you can go smaller to 16px if there's a need. The form elements are designed to fit with that 19px standard, maybe we need a full set to go with 16px text.

**Comment by dashouse** [comment]
I have done a test implementation (with some slight text tweaks) in GOV.UK Frontend
https://govuk-frontend-review-pr-608.herokuapp.com/components/radios
https://govuk-frontend-review-pr-608.herokuapp.com/components/checkboxes

**Comment by tombye** [comment]
I'm interested to know more about how the change in size effects the target size and spacing around it.
The current design for both is a bit short of those suggested by [Apple's design tips](https://developer.apple.com/design/tips/) and [Microsoft's guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/input/guidelines-for-targeting) but are fairly well tested for the types of user this effects the most - mouse and touch.

The demos provided do have a larger target area than that shown visually so it looks like that's part of the design. Any more info' on this would be very useful.

**Comment by nickcolley** [comment]
Related https://www.lukew.com/ff/entry.asp?1085

**Comment by owenm6** [comment]
@tombye We know these work pretty well on desktop but we don't have any services using these on smaller screens. The one thing I did do was increase the spacing between on smaller screens so that users don't accidentally select elements. 

The smaller screen implementation does need more thought.

**Comment by dashouse** [comment]
I am extremely hesitant to add comments here as I wasn't in the working group session. However...

GOV.UK Frontend does not reduce the physical size of form inputs on mobile, only the associated font size of label, therefore the radio or checkbox will remain the same size on desktop and mobile breakpoints.

It's also worth emphasising that touch device doesn't mean mobile, there are many users with hybrid machines, using both a mouse and a touch screen.

In my local test branch of @owenm6 's small radios I believe they will meet touch requirements if implemented in this way...

![screen shot 2018-04-27 at 08 15 00](https://user-images.githubusercontent.com/23356842/39350148-2d7e1412-49f5-11e8-8c7a-1185ee740af1.png)

For context, in this scenario the total size including bottom margin is only 5px smaller than the standard radios

![screen shot 2018-04-27 at 08 25 09](https://user-images.githubusercontent.com/23356842/39350351-d15bbdfa-49f5-11e8-9147-5a0a50ec4912.png)

**Comment by ignaciaorellana** [comment]
This proposal was reviewed by a panel of designers and frontend developers from GDS, HMRC, DWP, EA and Home Office on the 26 of April, 2018. It was reviewed against the ['useful' and 'unique' criteria](https://github.com/alphagov/govuk-design-system-backlog/blob/master/docs/CRITERIA.md) Thanks to the contributor @owenm6 

## Design review

The panel agreed that the pattern should not be published in the GOV.UK Design System until the following changes have been made.

## Recommendations

- The documentation needs more articulation, especially the section about where not to use.
- Needs to be clear that is for internal services only
- Explore how to document this: is it a variant of an existing thing? Or will it be presented as a separate thing?
- If this is only for services that look like GOV.UK, the examples should not use the logo and the transport font.
- Concerns about the touch size - if there is information about this, would be good to add it to the documentation
- It was suggested that this maybe can be a pattern for filtering results
- There is no clear need of why these need to be smaller

**Comment by owenm6** [comment]
#### The documentation needs more articulation, especially the section about where not to use.
I've updated this so I hope it is clearer. [Checkboxes](https://home-office-digital-patterns.herokuapp.com/components/checkboxes) and [Radios](https://home-office-digital-patterns.herokuapp.com/components/radios). Any feedback would be welcome. 

#### Needs to be clear that is for internal services only
This feels like an implementation issue if/when it makes it to the x-gov design system. In our design system it is marked for internal use only and stated for internal use in the lead paragraph.

#### Explore how to document this: is it a variant of an existing thing? Or will it be presented as a separate thing?
Again another implementation issue. It is a variant but right now it's not clear how this will be merged into the x-gov system. 

#### If this is only for services that look like GOV.UK, the examples should not use the logo and the transport font.
We are fixing this issue on the Home Office system, and removing transport font. But its part of a major piece of work which won't be published for a while. And as with the previous points, I don't know how this will be approached when it goes into the x-gov system.

#### Concerns about the touch size - if there is information about this, would be good to add it to the documentation
Not sure this is part of a unique/useful conversation. The implementation should probably be a separate conversation.

#### It was suggested that this maybe can be a pattern for filtering results
As a component, it could be used in many patterns. We have services using this component as part of a filter so if anything this point should help the component meet the useful criteria.

GOV.UK itself uses smaller checkboxes in its search filter. This component would bring consistency in use cases like that.

#### There is no clear need of why these need to be smaller
This is probably down to the way I communicated why we have done this. There is a clear user need. These component are being used on a number of Home Office services for good reasons. We use a typographic scale because elements do not always have a fixed importance - so some headings on a page are more important and visually bigger then others. The same is true for other UI elements. 

The current x-gov radios and checkboxes are designed for one thing per page and this is reflected in their size. Form elements on internal services are not always the most important element on a page. We have found the size unnecessary in these cases and can reduce the overall usability by creating a false hierarchy.

**Comment by joelanman** [comment]
> Needs to be clear that is for internal services only

I haven't been involved in the discussion so far, but I'm a bit worried by this response. I think components and patterns should be designed for tasks and contexts - user needs, not roles. It's totally possible that a public user could have the same needs and tasks as a government worker.

**Comment by stevenaproctor** [comment]
@joelanman And a government worker may have the same needs and tasks as a public user.

**Comment by timpaul** [comment]
Here's an example of small checkboxes used to filter a list on the Companies House website:

![image](https://user-images.githubusercontent.com/1590604/44298278-fe205400-a2d7-11e8-8460-42631ef149f2.png)

**Comment by ignaciaorellana** [comment]
Closing as this has been superseded by the #162
