### ISSUE TITLE
Add guidance about links

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system-backlog#137]
Suggest:

**Do not open links in a new tab**

Users can get confused if links open in new tabs - users can't use the back button in this situation.

I think it's generally more accessible to open links in the same tab.

If there is a real user need, add "(opens in a new tab)" to the end of the link text.

[WCAG guidance on warning users about new tabs](https://www.w3.org/TR/WCAG20-TECHS/G201.html)

**If you link to an external site, try to make that clear to users**

Also be very careful about where you link to.

This second part is in line with [GOV.UK content guidance](https://www.gov.uk/guidance/content-design/links).

[Guidance on the HMRC Design System](http://hmrc.github.io/assets-frontend/components/open-links-in-a-new-window-or-tab/index.html)

**Comment by nickcolley** [comment]
https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/

**Comment by stevenaproctor** [comment]
There definitely needs to be information about how to punctuate links, especially when the link is:

- at the end of a sentence
- the entire sentence and is separate from other content
- the entire sentence and is part of a larger paragraph

**Comment by timpaul** [comment]
I'm going to close this issue as it's covered by [another one](https://github.com/alphagov/govuk-design-system-backlog/issues/156) in the backlog.
