### ISSUE TITLE
Location Map

### ISSUE THREAD

**Issue by edent** [alphagov/govuk-design-system-backlog#139]
## What
> Give a brief description of the style, component or pattern you want to propose.

A map of a location on Earth. With labels on it. 

## Why

As a user, I want to see where a location is. I don't want to copy & paste addresses into a separate mapping app. 

As a user, I want to see the distance between locations. 

> Explain why you think this should be added to the GOV.UK Design System.
>
> - What evidence do you have that it's needed by multiple services across government?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the GOV.UK Design System? 

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

Openstreetmap would be a useful datasource - possibly using Leaflet, MapBox, or similar.

**Comment by timpaul** [comment]
Thanks for this Terence. We already have an issue raised for maps: #75. Do you think that it covers off your use case as well? If so, we'll close this one if that's OK.

**Comment by edent** [comment]
That's what I get for not searching properly!
