### ISSUE TITLE
Set a max-width on the examples container as to more accurately reflect what it will look like

### ISSUE THREAD

**Issue by davehaigh** [alphagov/govuk-design-system-backlog#142]
the examples wrapper is filling the entire width of the screen so components are rendered a lot wider than they are normally seen e.g open https://design-system.service.gov.uk/components/panel/ on a desktop pc. The 'confirmation panel' is very wide when normally its only 960px max.

I think the container should have a max width of 960px as to more accurately reflect the prototype kit.

<img width="1604" alt="image" src="https://user-images.githubusercontent.com/23551105/42097373-e621074a-7baf-11e8-8141-cc401b9ec590.png">

**Comment by joelanman** [comment]
This issue was moved to alphagov/govuk-design-system#418
