### ISSUE TITLE
Failed to load resource: https://design-system.service.gov.uk/javascripts/iframeResizer.map

### ISSUE THREAD

**Issue by davehaigh** [alphagov/govuk-design-system-backlog#143]
I'm getting a failed to load resource error 404 : https://design-system.service.gov.uk/javascripts/iframeResizer.map 

Using a MacBook, safari 11.1.1. 

Example page it's occurring on: https://design-system.service.gov.uk/components/panel/ 

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/23551105/42097507-337d188a-7bb0-11e8-8ef4-c81f754a69ff.png">

**Comment by joelanman** [comment]
This issue was moved to alphagov/govuk-design-system#417
