### ISSUE TITLE
Allow the 'Details' component to be used within form components

### ISSUE THREAD

**Issue by jfranciswebdesign** [alphagov/govuk-design-system-backlog#147]
## What
> Allow the 'Details' component to be used within form components (for example, radio buttons)
![image](https://user-images.githubusercontent.com/5270013/42311595-201c49b6-8036-11e8-9060-4565c64e0532.png)

## Why
The hint text item is not suitable for large amounts of 'help' content, or content which does not need to be seen by the majority of users.

**Comment by joelanman** [comment]
This issue was moved to alphagov/govuk-frontend#874
