### ISSUE TITLE
Allow details content to be selected and copied when expanded

### ISSUE THREAD

**Issue by andyjones1981** [alphagov/govuk-design-system-backlog#148]
The [details component,](https://design-system.service.gov.uk/components/details/) when expanded, closes when the content is clicked on, rather than the link causing the close action.

This causes a problem when a user wants to select and copy the expanded text. 

I am using this in a case tool which shows details of a message sent to an applicant, the case tool user might want to copy the update into another location but cannot do this.

On touch interfaces this does not occur and the text can be selected/copied without the panel closing.

I'll add that the[ Gov Elements](http://govuk-elements.herokuapp.com/typography/#typography-hidden-text) version didn't close when text was selected.

**Comment by andyjones1981** [comment]
@36degrees I just tested across IE11, Edge, FF and Chrome. Seems to be an issue isolated to IE11 and Edge only. I'll be honest I don't use chrome as my main browser, I use Edge. (Sorry should have x-tested first)

**Comment by 36degrees** [comment]
Great, thanks. I'm going to move this issue to alphagov/govuk-frontend so we can track it there.

**Comment by 36degrees** [comment]
This issue was moved to alphagov/govuk-frontend#911
