### ISSUE TITLE
Make it clear where to link Error summary to

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system-backlog#155]
It's not clear where the [Error summary](https://github.com/alphagov/govuk-design-system-backlog/issues/46) links should take people to

**Comment by colinrotherham** [comment]
A collection of variations as seen on GOV.UK Elements:

*Error summary links to `<legend>` id which focusses input*
http://govuk-elements.herokuapp.com/errors/example-form-validation-single-question-radio
http://govuk-elements.herokuapp.com/errors/example-form-validation-single-question-more-text

*Error summary links to `<label>` id which focusses input*
http://govuk-elements.herokuapp.com/errors/example-form-validation-single-question-text

*Error summary links to `<input>` id which receives focus*
http://govuk-elements.herokuapp.com/errors/example-form-validation-multiple-questions

I can't see any patterns on the design system that have both the error summary and error message components used together. Would be great to see this.

**Comment by colinrotherham** [comment]
For anyone else that finds this ticket, there's a more thorough demo on GOV.UK Frontend (used by the design system) here: http://govuk-frontend-review.herokuapp.com/examples/error-summary

![examples](https://user-images.githubusercontent.com/415517/46335807-996b4f80-c620-11e8-8347-37e049e523d1.png)

**Comment by nickcolley** [comment]
Research done by @36degrees : https://36degrees.github.io/linking-to-form-inputs/results/

**Comment by 36degrees** [comment]
This was addressed in https://github.com/alphagov/govuk-design-system/pull/634
