### ISSUE TITLE
using govukTable macro gives errot

### ISSUE THREAD

**Issue by satyajitsingh** [alphagov/govuk-design-system-backlog#161]
hi,

As per the directions and examples at https://design-system.service.gov.uk/components/table/ and Frontend-toolkit, I have downloaded the latest govuk-frontend and build a Node JS site. 
I have imported the govuktable macro as described, 
however when the page is loaded I get an error - Error: Unable to call `govukTable`, which is not a function. My code is as: 
<div class="column-two-thirds">
      {% set pastDayHtml %}
<h2 class="govuk-heading-l">Past day</h2>
{{ govukTable({
  head: [
........

can you help me here and let me know what could be the issue?

Thanks 

Satyajit Singh

**Comment by igloosi** [comment]
Hi @satyajitsingh thanks for getting in touch.

While this repository is about discussing components and patterns and not a support channel, we appreciate your frustration with a non working site. For code related issues we have a https://github.com/alphagov/govuk-frontend repository and a support email which you can find here https://design-system.service.gov.uk#support

If you're using our components for protoyping, we recommend using [GOV.UK Prototype kit](https://govuk-prototype-kit.herokuapp.com/docs) where components will be functioning as desired.

Should you be using our components in your custom (production) environment, we recommend you read our (Getting started in production guide)[https://design-system.service.gov.uk/get-started/production/]

I will close this issue, but if you encounter problems, please get in touch via above mentioned channels
