### ISSUE TITLE
Code verification

### ISSUE THREAD

**Issue by simonneb** [alphagov/govuk-design-system-backlog#174]
## What
A single reusable design for verifying contact details by sending that contact a code.

Design should include steps/pages for:

- requesting contact information
- confirming the sending of a code
- allowing entry of the code
- confirmation page as a result of a correct entry
- resending a code
- rejection page as a result of an incorrect entry

## Why
Some services use codes sent to customers as way of verify the identity of a user. These services currently use different language and design to fulfill this need. There is also a discrepancy in the length of the code provided between services.

## Anything else
Examples include: 
* [Get an annual MOT reminder](https://www.gov.uk/mot-reminder)
* [GOV.UK Notify](https://www.notifications.service.gov.uk)

Related to [Create an account](https://github.com/alphagov/govuk-design-system-backlog/issues/41)

**Comment by stevenaproctor** [comment]
Does this relate to [identifying users](https://github.com/alphagov/govuk-design-system-backlog/issues/25)?

**Comment by simonneb** [comment]
Yes - it does. Totally missed that when reviewing the backlog. Happy for this issue to be deleted!
