### ISSUE TITLE
Jump links (anchor navigation)

### ISSUE THREAD

**Issue by ashleyanderton** [alphagov/govuk-design-system-backlog#176]
## What
A list of designed links allowing users to jump to sections of a content heavy page.

## Why
- Currently other than default inline link styles and elements like the related link pattern, no navigation patterns exists for anchor navigation. 

- There are numerous content heavy pages that currently exist across gov.uk that could benefit from anchor navigation to prevent users from having to scroll for long periods, especially on mobile devices. We tested use of anchor links and in a lab environment users found them very useful. They currently have an overall engagement of around 5% on our BETA service.

- The overall need for anchor links was obtained via qualitative lab tests. The design for the jump links themselves were then AB tested on our live service with multiple variants. The current design was decided based on its increased engagement along with a lack of distraction from the content on the page.

## Live Example
A working example of jump links can be found on the BETA Explore careers website, part of the National Careers Service
https://beta.nationalcareersservice.direct.gov.uk/job-profiles/police-officer

## Research
A summary of the research performed along with the results of AB tests can be found on the following google doc:
https://drive.google.com/file/d/1Onz2hL-t1BO8l52rVUXgLcM5yVKzzlo4/view?usp=sharing

**Comment by stevenaproctor** [comment]
There are jump links on GOV.UK that appear as content links after the heading on a mainstream page and after the summary on a specialist page.

For example, [Universal Credit](https://www.gov.uk/universal-credit) and [Claim Income Tax relief for your employment expenses (P87)](https://www.gov.uk/guidance/claim-income-tax-relief-for-your-employment-expenses-p87).

**Comment by hannalaakso** [comment]
Hi @ashleyanderton 

Thanks a lot for adding this research 🙌 

Reviewing this, we think that the user need for your component and https://github.com/alphagov/govuk-design-system-backlog/issues/115 is the same. Would you agree with this? If you do, it would be great if you could add your content to that issue.

If you have any questions on this, please let us know, we'd be happy to discuss.

**Comment by ashleyanderton** [comment]
Hey @hannalaakso 

Comments made on #115 :+1:  Happy for this to be closed.

**Comment by nickcolley** [comment]
@ashleyanderton thanks! 😄
