### ISSUE TITLE
Add guidance to help users understand when they should be using the Crest / OGL on non-govuk hosted services

### ISSUE THREAD

**Issue by abbott567** [alphagov/govuk-design-system-backlog#192]
It would be good if some guidance could be published around the use of the HM Gov crest and the OGL licence in the footer component.

I've asked a few times on Slack, but I'm struggling to get an answer as to whether or not they fall under the same usage policy as the crown logo and the Transport font.

Thanks

**Comment by aliuk2012** [comment]
Hi @abbott567,

This is something our team have been talking about on over the past week and its something we would like to improve. 

I'm going to link this issue to https://github.com/alphagov/govuk-frontend/issues/1291 to help prioritise it. You will see that this is also part of an epic that we are working on https://github.com/alphagov/govuk-design-system/issues/777.

Would you mind if I closed this issue and you can track its progress through any of the above tickets?

**Comment by stevenjmesser** [comment]
We're going to close this issue as it should be addressed by [guidance about services not on GOV.UK](https://www.gov.uk/service-manual/design/making-your-service-look-like-govuk#if-your-service-isnt-on-govuk), please do comment or re-open it that guidance doesn't answer the question. 

The National Archives has [guidance](https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/copyright-assignments/frequently-asked-questions/) on the crest / Royal Arms.
