### ISSUE TITLE
Public user verification

### ISSUE THREAD

**Issue by rydal** [alphagov/govuk-design-system-backlog#195]
This is a means of verifying people are who they claim to be at the request of the person wishing to affirm who they are. It would be useful when meeting new people from internet dating sites etc.

It's based of an aspect of the couch surfing website whereby users can prove they are who they say they are with the website confirming identity using text, physical address and bank detail confirmation.

Those wishing to prove their identity have a login and a code, similar to a password they can provide to others allowing the person verifying them to receive detail's of their town and maybe passport picture as provided on an opt in basis.

As a currently running feature of couch surfing I believe this will prove popular. Giving peace of mind to the public that the people they are meeting are who they claim to be.

Thanks.
Rob Brew

**Comment by rydal** [comment]
Ps. My email address is rob@rydal.org

**Comment by amyhupe** [comment]
Hi Rob,

Thanks for your comment.

This is the community backlog for the [GOV.UK Design System](https://design-system.service.gov.uk/) where we discuss upcoming components and design patterns for government services.

I just wanted to check if you meant to comment here.

Thanks,

Amy

**Comment by nickcolley** [comment]
@rydal I've removed your email address to make sure you do not get spammed, if you want to contact us directly you can get in touch: https://design-system.service.gov.uk/get-in-touch/

**Comment by rydal** [comment]
Hi Amy.

Yes i menat to detail this here as a proposed component of the gov.uk system.

Thanks,
 Rob Brew.

**Comment by 36degrees** [comment]
Hi Rob,

This would be more than just a user interface component or a pattern for doing something – it would be a service in its own right, and would need its own business case and a team to support it. As such, it's out of the scope of what the Design System is for, so we're going to close this.

Thanks for your understanding.

Ollie
