### ISSUE TITLE
Understand the impact of an emergency on your service

### ISSUE THREAD

**Issue by govuk-design-system** [alphagov/govuk-design-system-backlog#212]
Use this issue to discuss [this pattern in the GOV.UK Design System](https://design-system.service.gov.uk/patterns/understand-the-impact-of-an-emergency/).

**Comment by CharlotteDowns** [comment]
## Retiring 'Help users to understand the impact of an emergency on your service' pattern

In [GOV.UK frontend release 3.10.0](https://github.com/alphagov/govuk-frontend/releases/tag/v3.10.0) we retired the 'Help users to understand the impact of an emergency on your service' pattern to avoid duplication with guidance suggested in the [notification banner component](https://design-system.service.gov.uk/components/notification-banner/).
