### ISSUE TITLE
Cookie consent: a PECR compliant and accessible solution from Cabinet Office Digital

### ISSUE THREAD

**Issue by Tony-CabOff** [alphagov/govuk-design-system-backlog#216]
![image](https://user-images.githubusercontent.com/58213575/110804706-52b1c300-8278-11eb-9e3d-f682555d6aef.png)
### What and why
Here in the Cabinet Office's CDIO Directorate we help policy teams assure and deliver on their proposals for digital services. We recognised there was an urgent need to create a cookie tracking consent solution for users of services we work with that don’t reside on the GOV.UK platform, though they may be reachable from the platform. 

This solution is available for service teams and individuals to use with accompanying implementation guidance. It consists of the following components:

> - a cookie consent banner;*
> - a HTML cookie settings preference page template - configured to be “off” or “opt-in” by default; and,
> - a HTML cookie policy page template. 

In combination, these components provide service users with the choice to opt in to non-essential cookie tracking in a fully informed and unambiguous manner, and with equivalence in access to opt in/opt out functionality.

### How to access it
All three items have been user tested, confirmed as fully compliant with the Privacy and Electronic Communications Regulations (“cookie law”) by the Cabinet Office Data Protection Officer, make use of GOV.UK Design System components and have been independently audited to meet the legally required standard of accessibility; [WCAG 1, level AA](https://www.gov.uk/service-manual/helping-people-to-use-your-service/understanding-wcag).

We've created versions for use in [Node.js](https://github.com/cabinetoffice/co-cookie-consent), [Wordpress](https://github.com/cabinetoffice/cookie-consent-wp/tree/master/co-cookie-consent) and [Salesforce](https://github.com/cabinetoffice/cookie-consent-sfdc) as these are the most common platforms used by our services. Click on the links to locate the respective GitHub repositories.

You can find examples of them in use on live services such as [Submit trade union facility time data](https://submit-facility-time.cabinetoffice.gov.uk/register/organisation) (Node.js), the [Civil Service Commission](https://civilservicecommission.independent.gov.uk/) (Wordpress) and the [Honours Nomination service](https://www.nominate-uk-honour.service.gov.uk/HAS_Login_Page?startURL=%2F) (Salesforce)

If you’re working on a Cabinet Office service and need help implementing this solution, please contact us on this channel. We’re also happy to share insight into the thinking and development process behind what we have created more widely. 

*_We're currently updating the repositories for this component in Wordpress and Node.js.

**Comment by Tony-CabOff** [comment]
Thank you. No decision; It was a consequence of the [Design System button component](https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2Falphagov%2Fgovuk-frontend%2Fblob%2Fmaster%2Fsrc%2Fgovuk%2Fcomponents%2Fbutton%2Ftemplate.njk) [line 15 and 44] which generates an anchor with the button role (instead of an actual button) when href is passed/set:
		`{{ govukButton ({ text: "Set cookie preferences", classes: "govuk-button--secondary govuk-!-margin-bottom-4", href: cocc_pref_href }) }}`

**Comment by edwardhorsford** [comment]
> Nice work, out of interest what was the decision based around when making the link ("set cookie preferences") look like a button when it is not? It also has the role of button.
> 
> To clarify, the Civil Service Commission uses a button element for the "Set cookie preferences" action but all it does is redirect to another page. In that instance I think it is a mistake and the anchor tag should be used.
> 
> The Cabinet Office correctly uses an anchor, but as I see it also incorrectly uses the role of button - and styles the link to look like a button.

@Tony-CabOff (or his team) has chosen to make both options look like buttons - I presume to give equal weight to them and because they're trying to reflect the choice / actions the user has to take. This feels sensible, and matches what GOV.UK does too.

What's important is that the behaviour of the element matches what it looks like - that way it works for assistive technologies. In this case, it looks like a button, and because of the role (and js shim), it behaves like a button.

The design system supports buttons like this because it's a common need - to make things look like buttons where a literal button html element wouldn't work. These have have been tested extensively over the years and test very well with users. There's 

---

Buttons vs links is a common discussion - I suggest adding a comment to the [Button component ](https://github.com/alphagov/govuk-design-system-backlog/issues/34)or [this issue I raised](https://github.com/alphagov/govuk-design-system/issues/1185) about better documenting the current button component.

**Comment by MalcolmVonMoJ** [comment]
We have opted for a similar design, but opted for a green "primary" button for the accept all.  

We have discussed it in [the other discussion on cookie banners](https://github.com/alphagov/govuk-design-system-backlog/issues/12#issuecomment-646062621).

![image](https://user-images.githubusercontent.com/32877315/85123946-0a053600-b221-11ea-97d0-0f2c0ca7cbd2.png)

**Comment by anevins12** [comment]
Thanks for the clarification!

**Comment by Tony-CabOff** [comment]
> We have opted for a similar design, but opted for a green "primary" button for the accept all.
> 
> We have discussed it in [the other discussion on cookie banners](https://github.com/alphagov/govuk-design-system-backlog/issues/12#issuecomment-646062621).
> 
> ![image](https://user-images.githubusercontent.com/32877315/85123946-0a053600-b221-11ea-97d0-0f2c0ca7cbd2.png)

Nice work. We thought about the green button and various combinations of this in the banner during build but opted to heed the GOV.UK Design System advice to have only one CTA button on a web page. For us this meant having no green button in the banner as it may dilute the import of this navigational function where it appears lower down on the web page.

**Comment by MalcolmVonMoJ** [comment]
That is an interesting point.  It is taking that advice very strictly.  I would consider the cookie banner to be a separate page in regard to that advice.  The two green buttons are not rivals, click on _Accept all cookies_ and the green navigation button is still waiting for you, prominent as ever.

**Comment by Tony-CabOff** [comment]
> That is an interesting point. It is taking that advice very strictly. I would consider the cookie banner to be a separate page in regard to that advice. The two green buttons are not rivals, click on _Accept all cookies_ and the green navigation button is still waiting for you, prominent as ever.

Indeed, as indicated we were thinking about reducing [cognitive load](https://www.nngroup.com/articles/minimize-cognitive-load/) for the user but also we aimed to maintain as much as an equivalence between how easy it was to opt in to cookie tracking and setting preferences/opting out. [ICO guidance](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/consent/), reflecting GDPR and PECR, asks that consent be as easy to grant as it is to withdraw. Distinguishing colour on either button, we thought, could tip the balance of perception in this context.

**Comment by joelanman** [comment]
Agree with @Tony-CabOff. Green buttons should be used as the primary call to action. From a users point of view, there is no primary action - it should be choice for them to make.

**Comment by awjdigital** [comment]
Hi @Tony-CabOff Following a DAC audit which picked up several issues with a 3rd party control (the one ICO uses) we were pointed in the direction of this control. (I'm assuming you're the same Tony that DAC spoke to about us?)

I've started to implement this in the new site and while the banner shows, hides, displays the preferences, but doesn't seem to be saving the actual preference selected. As soon as the page reloads, it just displays the banner again and no value is being stored. 

Would anyone be able to help me out with it? I can't see what i've got going wrong.

**Comment by mark-affinity** [comment]
Hi @awjdigital are you implementing this to a wordpress site or other?

**Comment by awjdigital** [comment]
> Hi @awjdigital are you implementing this to a wordpress site or other?

It's a website built using node which utilises our own organisation's frontend which extends the GOV Frontend.

**Comment by mark-affinity** [comment]
> @mark-affinity It's a website built using node which utilises our own organisation's frontend which extends the GOV Frontend. I can share a link to the beta site to see what's happening, I just can't share the link publicly at the moment.

Did the code supplied include the <script type="text/javascript">setupCookieChoices();</script> that should go before </body>?

**Comment by awjdigital** [comment]
@mark-affinity No it doesn't and there's no function in the node solution called setupCookieChoices() that I can see.

**Comment by awjdigital** [comment]
Until I find out there's something missing in the Node code example, i'm calling a function I've added to set the values of the radios based on the selected preference. And in the init function a routine to decide whether to show/hide the banner based on stored cookie. 

This appears to work and when preference changed and saved clears cookies out. Clearing cookies in app displays the banner again - all seems to work as exptected. 

Init
```
this.readCookie('seen_cookie_message') ? this.show("cocc-banner") : this.hide("cocc-banner");
```

setup preference

```
    this.setupCookiePreferences = function () {

        var policy = this.retrieveCookiePolicy()

        if (policy.usage === true) {
            document.getElementById("cocc-pref-consent").checked = true
        }

        if (policy.usage === false) {
            document.getElementById("cocc-pref-consent-2").checked = true;
        }

    }
```

**Comment by cmok-xansium** [comment]
@awjdigital I've updated co-cookie-consent README.md and push a minor changes. Please fetch the latest repo and let me know if have problem with the instructions.
