### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by govuk-design-system** [alphagov/govuk-design-system-backlog#22]
## What

Examples of common error pages, including:

- Page not found (404)
- Internal server error (500)

Example on 'Renew your passport'

![screen shot 2018-02-20 at 12 38 04](https://user-images.githubusercontent.com/33149131/36424369-f684147c-163a-11e8-92b5-c20e1565eefb.png)

![screen shot 2018-02-20 at 13 36 14](https://user-images.githubusercontent.com/33149131/36426811-3c741d26-1643-11e8-8fc7-dcd63bd84892.png)

Example of 404 on 'Register to vote'
![screen shot 2018-02-21 at 10 42 17](https://user-images.githubusercontent.com/33149131/36475883-13e41a26-16f4-11e8-88bd-3435deb74a73.png)

## Why

All services experience errors and users should have a consistent experience when this happens.

## Anything else

- Read draft guidance on [Error pages: Dropbox Paper](https://paper.dropbox.com/doc/icpXYcakR5K9B6DfU5R8d)
- DWP have a version [Error pages: DWP design patterns](https://dwp-patterns.herokuapp.com/errorpages)
- HMRC have a version on [404 pages: HMRC design patterns](http://hmrc.github.io/assets-frontend/patterns/404-page/index.html)
- HMRC also has a version for [500 pages: HMRC design patterns](http://hmrc.github.io/assets-frontend/patterns/technical-problem/index.html)

**Comment by owenm6** [comment]
And this - https://home-office-digital-patterns.herokuapp.com/patterns/error-pages

**Comment by timpaul** [comment]
Closing as this issue has been replaced by #130 and #129
