### ISSUE TITLE
Pilot a review process for the backlog

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system-backlog#221]
Pilot a process for systematically reviewing items in the backlog and generating issues and PRs for their related component or pattern. For this process we're only focussing on things that have already been published.

**Comment by timpaul** [comment]
Here's a proposed new format for the initial comment of each backlog item:

**Comment by timpaul** [comment]
Use this page to discuss the [text input component](https://govuk-design-system-production.cloudapps.digital/components/text-input/) in the GOV.UK Design System. 

There is a separate discussion page for [text input prefixes and suffixes](https://github.com/alphagov/govuk-design-system-backlog/issues/134).

_This page was last reviewed on 29 September 2020._

### Links
- [view this component in the GOV.UK Design System](https://govuk-design-system-production.cloudapps.digital/components/text-input/)
- [view a list of open issues and pull requests for this component](https://github.com/search?q=label%3A%22text+input%22+is%3Aopen+repo%3Aalphagov%2Fgovuk-design-system+repo%3Aalphagov%2Fgovuk-frontend+repo%3Aalphagov%2Fgovuk-prototype-kit&type=issues)
- [view the commit history of the guidance for this component](https://github.com/alphagov/govuk-design-system/commits/master/src/components/text-input)
- [view the commit history of the code for this component](https://github.com/alphagov/govuk-frontend/commits/master/src/govuk/components/input)

**Comment by timpaul** [comment]
Here's a proposed checklist of actions for each backlog item:

- [ ] hide any outdated, off-topic or resolved comments
- [ ] capture significant research findings and update the 'Research' section of the guidance
- [ ] capture significant design decisions and update the 'How it works' section of the guidance
- [ ] capture issues, bugs and feature requests and raise them in the appropriate repo
- [ ] update the 'last reviewed' date in the initial comment

**Comment by timpaul** [comment]
QUESTIONS: 

- is there value to users in providing links to open issues and PRs?
- is there value to users in providing links to the commit history of the guidance and code?

**Comment by timpaul** [comment]
So far, my review of the text input backlog item has generated these issues:

- [Some users think that prefixes are clickable](https://github.com/alphagov/govuk-frontend/issues/1973)

And these PRs:

- [Explain how fixed widths are calculated](https://github.com/alphagov/govuk-design-system/pull/1366)
- [Explain why prefixes and suffixes are outside inputs](https://github.com/alphagov/govuk-design-system/pull/1365)
- [Add research findings from backlog](https://github.com/alphagov/govuk-design-system/pull/1363)

**Comment by timpaul** [comment]
Going to try the details component next...

**Comment by timpaul** [comment]
### Examples of useful GitHub search patterns


1. _Open issues in our repos that contain the text "text input" but haven't been given the "text input" label..._

```
"text input" 
-label:"text input" 
is:open 
repo:alphagov/govuk-design-system 
repo:alphagov/govuk-frontend 
repo:alphagov/govuk-prototype-kit
```

**Comment by kellylee-gds** [comment]
@timpaul going to close and move into done for now
