### ISSUE TITLE
RED AMBER GREEN - traffic light - data quality

### ISSUE THREAD

**Issue by tessharwoodkpmg** [alphagov/govuk-design-system-backlog#222]
## What
> Give a brief description of the style, component or pattern you want to propose.
Component is a traffic light to indicate whether something is in a Red, Amber or Green state.
![Amber pic](https://user-images.githubusercontent.com/72930212/96142339-e2398c80-0ef9-11eb-9bc5-9c5450cdf071.png)

## Why
> Explain why you think this should be added to the GOV.UK Design System.
>
The Red-Amber-Green, RAG, rating system is very useful to indicate and prompt actions from users. 
We need to start setting standards for our open data users, and RAG has almost unanimously been requested as the method for communicating this to users.

> - What evidence do you have that it's needed by multiple services across government?
It is clear that as open data becomes more ubiquitous, data standards and quality will need to be measured and users need an easy to follow traffic light system to indicate whether further action is required and how much is required. As well as users of open data for understanding the risks and rewards of using data. 

> - What evidence do you have that it meets the needs of the users of those services?
Over 30 user interview conducted indicated a preference for this metric.

> - Have you checked that it doesn't already exist in the GOV.UK Design System? 
Yes.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

**Comment by christopherthomasdesign** [comment]
Hi @tessharwoodkpmg, thanks for your comment.

A red-amber-green status as described could cause issues for colour blind users and I'm not sure it would pass [WCAG success criterion 1.4.1 use of colour](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html). While colour can be useful to convey information, it should not be the only way information is conveyed. You could argue that the placement of the lights, mirroring the configuration of traffic lights in the UK, adds extra context to the image than just the colours. But I wouldn't assume this knowledge is universal or that the meaning would be immediately clear to all users.

The user need you describe could possibly be met using the [tag](https://design-system.service.gov.uk/components/tag/) component, which has several variants in different colours. These use words and colour to convey meaning. It's worth choosing the words carefully – whilst 'red' 'amber' and 'green' might be enough to resolve the accessibility issue mentioned above, there may be a more relevant or understandable set of statuses you can apply to things in your service.

Hope that helps!

**Comment by hannalaakso** [comment]
@tessharwoodkpmg Thanks for raising this. As we haven't heard back from you, I'm going to close this issue. If you do have additional user research and information about this meeting WCAG please let us know and we can re-open the issue for discussion.
