### ISSUE TITLE
Select - Select add HTML support for OptGroup

### ISSUE THREAD

**Issue by andrewcharnley** [alphagov/govuk-design-system-backlog#232]
Couple lines needed to the macro.

[govukSelectGroups.njk.zip](https://github.com/alphagov/govuk-design-system-backlog/files/6925349/govukSelectGroups.njk.zip)

**Comment by hannalaakso** [comment]
@andrewcharnley I'm going to close this issue as the GOV.UK Design System team are not able to accept contributions as zip files. 

You can follow the general instructions here on how to [Raise a pull request in GitHub](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to modify/add files to a repository. If you wish to modify the [select component](https://design-system.service.gov.uk/components/select/), you should raise the pull request in [this repository](https://github.com/alphagov/govuk-frontend). 

However, we would recommend that you first [Raise an issue](https://github.com/alphagov/govuk-frontend/issues/new?assignees=&labels=feature+request%2C+awaiting+triage&template=feature-request.md&title=) for the feature you wish to add. This will allow the GOV.UK Design System team to review the proposal and raise any queries. Doing this first will increase the likelihood of your suggested feature and then your pull request being accepted.

Thanks for your interest in the [GOV.UK Design System](https://design-system.service.gov.uk/) 👍

**Comment by andrewcharnley** [comment]
This was a feature request, the zip was a bonus.

**Comment by hannalaakso** [comment]
@andrewcharnley Thanks for clarifying 👍 

Would you be okay to [Raise an issue](https://github.com/alphagov/govuk-frontend/issues/new?assignees=&labels=feature+request%2C+awaiting+triage&template=feature-request.md&title=) for the feature you wish to add? The answers to the questions in the template help the team to understand the user need and use cases for new features that are proposed.
