### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by andyjones81** [alphagov/govuk-design-system-backlog#270]
## What

Guidance for, and using, charts in services, for example: bar charts and pie charts.

## Why

There is no current issue in the backlog for charts. I have received a few requests from teams in DfE about how best to use charts or if there are patterns or components to make use of. 

There is an inconsistent approach at the moment with different charting libraries being used, some more accessible than others. 

Additionally, I am seeing an increase in embedded charting being used, where Power-BI iframes are presenting data and charts in inaccessible formats. 

Nothing in the [project board ](https://github.com/orgs/alphagov/projects/4) or the [backlog project](https://github.com/orgs/alphagov/projects/43/views/1)

**Comment by joelanman** [comment]
there is an issue here:
https://github.com/alphagov/govuk-design-system-backlog/issues/16

**Comment by stevenjmesser** [comment]
I'm closing this as it should be addressed in https://github.com/alphagov/govuk-design-system-backlog/issues/16.
