### ISSUE TITLE
Link to Cookies Page before Options please 

### ISSUE THREAD

**Issue by Kate-Nicolson** [alphagov/govuk-design-system-backlog#284]
## What
> The cookie banner layout and tab-order has text then Accept then Reject the Cookies Link.
> I think the cookies link should be before the Accept button

## Why
> I think currently it is a poor design in relation to thinking about the user journey of users with screen readers
> In accepting cookies it is supposed to be informed consent - but the user isn't presented with the link to more details about the cookies until after the choice to accept them.
> I think the pattern should be updated to either put the link before the 2 buttons, or have the link to the cookies be in the wording above the 2 options.

#accessibility

**Comment by querkmachine** [comment]
Hi @Kate-Nicolson,

Thanks for this feedback. I think this would fit better being added to the conversation in #12, so I'm going to link this over there and close this issue for now. 

Feel free to raise any further concerns with the cookie banner over on #12. Thanks again!
