### ISSUE TITLE
Broken Link -> shotgun-and-firearm-certificates

### ISSUE THREAD

**Issue by 0xE69** [alphagov/govuk-design-system-backlog#286]
## What
> Give a brief description of the style, component or pattern you want to propose.

There is a broken link here: 

The broken link is when you click on the green "Start Now" Button. 

https://www.gov.uk/find-licences/shotgun-and-firearm-certificates

## Why

Fixing the link will be helpful, No improvements needed. 

Sorry
We can't find the page you are looking for
This page has been moved, deleted or does not exist. Please use the search box below to find the one you need.

Search the Metropolitan Police Service website

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

**Comment by querkmachine** [comment]
Hi @0xE69,

This GitHub repo is for discussing components and patterns relevant to the [GOV.UK Design System](https://design-system.service.gov.uk/). We aren't responsible for and are unable to change the content of the GOV.UK website.

If you haven't already, please instead click the "Report a problem with this page" button near the bottom of the Shotgun and firearm certificates page and report the problem there. That should direct it to the correct team. 

Thank you!
