### ISSUE TITLE
Conveying Importance

### ISSUE THREAD

**Issue by lazybones-uk** [alphagov/govuk-design-system-backlog#293]
Hi,
Authors would use this component to emphasis the importance of one paragraph over another, or to provide a hint or something right? I'm wondering why the code doesn't use a p tag to show it's a paragraph, or have anything to convey importance like a label, em, or strong.

Semantically, It's only conveying that it's not a paragraph. Visually, it's the complete opposite, I don't get it, am I missing something here?

wouldn't something like below be a more accurate markup?
`<p class="govuk-inset-text"><span class="govuk-visually-hidden"><strong>Please Note: </strong></span>Text I want people to take note of</p>`.

**Comment by joelanman** [comment]
I think you're referring to the [Inset text component](https://design-system.service.gov.uk/components/inset-text/)

It's interesting to compare to Warning, that does include hidden text:

https://design-system.service.gov.uk/components/warning-text/

Unfortunately `<strong>` doesn't commonly convey anything to screen reader users:

https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-the-use-of-emphasis-in-text

**Comment by lazybones-uk** [comment]
Yes, I was referring to the Inset text component.
I thought `<strong>` did convey to screen readers, I read the article in the link you posted. Interesting stuff, it's unfortunate that JAWS and NVDA don't default to announcing them but all we can do is use the correct markup and hope that they will some day.
