### ISSUE TITLE
Superscript and subscript

### ISSUE THREAD

**Issue by blowfishsoup** [alphagov/govuk-design-system-backlog#294]
## What
> Give a brief description of the style, component or pattern you want to propose.

## Why
> Explain why you think this should be added to the GOV.UK Design System.
>
> - What evidence do you have that it's needed by multiple services across government?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the GOV.UK Design System? 

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

**Comment by blowfishsoup** [comment]
We have a service that uses scientific measurements (e.g. cubic metres - m3). We'd like to be able to use superscript to avoid user confusion where we present these values back to the user (e.g. 3m3). Is there currently an option to use superscript (or subscript) and, if not, is it something that's being considered?

**Comment by owenatgov** [comment]
Hi @blowfishsoup 👋🏻 

This can be done without any intervention from the design system team using the [sup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup) and [sub](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub) html tags. You can use them in the content of your service like so:

```html
<p class="govuk-body">My content<sup>my superscript</sup> more content<sub>my subscript</sub>.</p>
```

On a GOV.UK Frontend service this will render like so:
![example of govuk-body content with sub and sup tags](https://github.com/alphagov/govuk-design-system-backlog/assets/64783893/8ab3d851-62e2-483c-b38b-43192bfdb45d)

I'm going to close this issue and I believe this has answered your question but please feel free to reopen it if you still feel your query hasn't been answered.
