### ISSUE TITLE
Fill in a form

### ISSUE THREAD

**Issue by govuk-design-system** [alphagov/govuk-design-system-backlog#50]
Use this issue to discuss [this pattern in the GOV.UK Design System](https://govuk-design-system-production.cloudapps.digital/patterns/fill-in-a-form/).

**Comment by christaylor-hod** [comment]
Get a 404 not found with the link in this ticket

**Comment by 36degrees** [comment]
> Get a 404 not found with the link in this ticket

Thanks for raising, @christaylor-hod!

It looks like the 'fill in a form' pattern was removed in https://github.com/alphagov/govuk-design-system/commit/b3b8fcc115414fdea5833de532d06c3238fa793f (as part of https://github.com/alphagov/govuk-design-system/pull/348) – the guidance that was in the pattern ended up remaining in the service manual as the [Structuring forms guide](https://www.gov.uk/service-manual/design/form-structure).

@amyhupe @timpaul do you think it makes any sense to keep this issue around, or should we just close this?

**Comment by amyhupe** [comment]
I think we can close it
