### ISSUE TITLE
Pay for something

### ISSUE THREAD

**Issue by govuk-design-system** [alphagov/govuk-design-system-backlog#79]
Also known as: checkout, shopping basket, shopping cart.

## What
Help users review, amend and purchase one or more items.

## Anything else
- Example: [GOV.UK Pay](https://www.payments.service.gov.uk/)
- Related patterns: #80 Payment details

**Comment by joelanman** [comment]
Is this needed outside of GOV.UK Pay?

**Comment by timpaul** [comment]
Good point. I think there might be 3 arguments for including something:

1) GOV.UK Pay doesn't cover all use cases relating to paying for something
2) Not everyone will be able to use GOV.UK Pay
3) The pattern could serve as a useful way of telling people about GOV.UK Pay

What do you think?

**Comment by mikeash82** [comment]
@rpowis commented on 31 Jan 2017

![image](https://cloud.githubusercontent.com/assets/1752124/22468297/0a837c44-e7c8-11e6-8559-9846f25710a2.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468233/d72de334-e7c7-11e6-994f-baeaece8f516.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468268/f2b5eee4-e7c7-11e6-8949-24a8793b2431.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468172/b563318c-e7c7-11e6-89eb-f334ce6eb0ad.png)

# Hackpad Discussion

https://designpatterns.hackpad.com/Payment-screens-c6ujPWbCoeY

**Comment by Ciandelle** [comment]
Huge overlap with #80 payment card details and #149 bank details which are both now published.
