### ISSUE TITLE
Sending text messages

### ISSUE THREAD

**Issue by govuk-design-system** [alphagov/govuk-design-system-backlog#91]
## What
How and when to send text messages, with example templates.

## Anything else
- Read draft guidance on [Notifications: Dropbox Paper](https://paper.dropbox.com/doc/Sending-notifications-by-email-text-message-or-letter-3JIvSsDSBOeoZIEdjkC4Z)
- Example: [GOV.UK Notify](https://www.notifications.service.gov.uk/)

**Comment by quis** [comment]
See also: https://www.gov.uk/service-manual/design/sending-emails-and-text-messages

**Comment by rafaldrewnowski** [comment]
In 'Get MOT reminder' service users get a text or email notification about expiring MOT test for a vehicle they subscribed for. Reminders are sent one month and two weeks before MOT is due. 

Current template for text message is as follows:

MOT reminder: The MOT for {REGISTRATION NUMBER} is due by {DATE OF EXPIRY}. Book the test now. The MOT test changed on 20/05/2018, find out more at 
https://www.gov.uk/government/news/mot-changes-20-may-2018. Give us feedback at https://www.gov.uk/mot-survey. To unsubscribe reply STOP {REGISTRATION NUMBER}

**Comment by Ciandelle** [comment]
There's [guidance](https://www.gov.uk/service-manual/design/sending-emails-and-text-messages) in the service manual guidance on this subject.
